pipeline {
    agent any

    environment {
        IMAGE = "sample-app:latest"
        CONTAINER = "sample-app"
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                bat "docker build -t ${IMAGE} ."
            }
        }

        stage('Stop Old Container') {
            steps {
                bat "docker rm -f ${CONTAINER} || true"
            }
        }

        stage('Run New Container') {
            steps {
                bat "docker run -d --name ${CONTAINER} -p 3000:3000 ${IMAGE}"
            }
        }
    }
}
